name = "personalstylist-api"
main = "api-worker.ts"
compatibility_date = "2026-03-09"


[triggers]
crons = ["0 * * * *"]

[placement]
region = "gcp:us-east4"

[vars]
POLAR_SERVER = "production"

[[r2_buckets]]
binding = "PROFILE_PHOTOS"
bucket_name = "personalstylist-profile-photos"
