create or replace function public.set_current_timestamp_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;
create table if not exists public.customer_style_profiles (
  user_id uuid primary key references auth.users (id) on delete cascade,
  email text not null,
  height_cm integer not null check (height_cm between 50 and 280),
  weight_kg numeric(5, 1) not null check (weight_kg > 20 and weight_kg < 500),
  location_query text not null,
  location_name text not null,
  country_code text,
  timezone text not null,
  latitude double precision not null,
  longitude double precision not null,
  photo_object_key text,
  photo_content_type text,
  daily_email_enabled boolean not null default true,
  preferred_locale text not null default 'en-US',
  last_daily_sent_local_date date,
  last_daily_sent_at timestamptz,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create index if not exists customer_style_profiles_daily_enabled_idx
  on public.customer_style_profiles (daily_email_enabled, timezone);

alter table public.customer_style_profiles enable row level security;

drop policy if exists "Users can read their own style profile" on public.customer_style_profiles;
create policy "Users can read their own style profile"
  on public.customer_style_profiles
  for select
  using (auth.uid() = user_id);

drop policy if exists "Users can insert their own style profile" on public.customer_style_profiles;
create policy "Users can insert their own style profile"
  on public.customer_style_profiles
  for insert
  with check (auth.uid() = user_id);

drop policy if exists "Users can update their own style profile" on public.customer_style_profiles;
create policy "Users can update their own style profile"
  on public.customer_style_profiles
  for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop trigger if exists set_customer_style_profiles_updated_at on public.customer_style_profiles;
create trigger set_customer_style_profiles_updated_at
before update on public.customer_style_profiles
for each row
execute function public.set_current_timestamp_updated_at();

create table if not exists public.daily_style_delivery_logs (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  delivery_date date not null,
  timezone text not null,
  email text not null,
  status text not null check (status in ('pending', 'sent', 'skipped', 'failed')),
  weather_snapshot jsonb,
  generated_brief text,
  resend_email_id text,
  error_message text,
  sent_at timestamptz,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  unique (user_id, delivery_date)
);

create index if not exists daily_style_delivery_logs_status_idx
  on public.daily_style_delivery_logs (status, delivery_date desc);

alter table public.daily_style_delivery_logs enable row level security;

drop policy if exists "Users can read their own delivery logs" on public.daily_style_delivery_logs;
create policy "Users can read their own delivery logs"
  on public.daily_style_delivery_logs
  for select
  using (auth.uid() = user_id);

drop trigger if exists set_daily_style_delivery_logs_updated_at on public.daily_style_delivery_logs;
create trigger set_daily_style_delivery_logs_updated_at
before update on public.daily_style_delivery_logs
for each row
execute function public.set_current_timestamp_updated_at();
